In [6]:
#import sys.path
from scripts.helpers import load_data

In [7]:
path= "https://raw.githubusercontent.com/allaccountstaken/camels-risk-profile-classification/main/data/camel_data_after2010Q3.csv"
df = load_data(path)

In [13]:
df.head()

,AsOfDate,Target,EQTA,EQTL,LLRTA,LLRGL,OEXTA,INCEMP,ROA,ROE,TDTL,TDTA,TATA
1252,12/31/2009,1,0.008644,0.010834,0.092012,0.115320,0.025272,-593.165644,-0.136337,-15.772594,1.232007,0.982991,0.112894
3287,12/31/2009,1,0.078408,0.189268,0.003523,0.008503,0.022508,20.900000,0.003875,0.049421,2.205290,0.913583,0.358536
5672,12/31/2009,1,0.002112,0.003144,0.066657,0.099216,0.034378,-323.516556,-0.058455,-27.677620,1.383128,0.929228,0.135505
5702,12/31/2009,1,0.015982,0.021148,0.030035,0.039743,0.039763,-153.596354,-0.049911,-3.123001,1.195850,0.903733,0.094482
8221,12/31/2009,1,0.011542,0.013393,0.041798,0.048502,0.038922,-217.888889,-0.069640,-6.033846,1.145630,0.987286,0.098334